name: 'Setup Project'
description: 'Common setup steps for all CI jobs'
inputs:
  gradle_key:
    description: 'Encryption key for Gradle'
    required: true
runs:
  using: "composite"
  steps:
    - name: set up JDK 17
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Validate Gradle Cache Key
      shell: bash
      run: |
        if [ -z "${{ inputs.gradle_key }}" ]; then
          echo "::error::gradle_key is empty! Check if the secret is passed in the main workflow."
          exit 1
        else
          echo "âœ… gradle_key found."
        fi

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
      with:
        cache-encryption-key: ${{ inputs.gradle_key }}
        cache-read-only: false
        dependency-graph: generate-and-submit