[versions]
androidGradlePlugin = "8.12.1"
kotlinGradlePlugin = "1.9.24"
googleServicesGradlePlugin = "4.4.3"
crashlyticsGradlePlugin = "3.0.6"
detektGradlePlugin = "1.23.8"

junit = "4.13.2"
extJunit = "1.3.0"
espressoCore = "3.7.0"

composeBom = "2025.08.00"
firebaseBom = "34.1.0"

kotlin = "2.2.10"
kotlinComposeCompiler = "2.2.10"
ksp = "2.2.10-2.0.2"
kotlinSerialization = "2.2.10"
coreKtx = "1.17.0"
lifecycleRuntimeKtx = "2.9.2"
activityCompose = "1.10.1"
material3 = "1.3.2"
daggerHilt = "2.57.1"
androidxHilt = "1.2.0"
work = "2.10.3"
timber = "5.0.1"
room = "2.7.2"
security = "1.1.0"
kotlinxSerializationJson = "1.9.0"

[libraries]
# AndroidX Core
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }

# Compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-compose-icons = { group = "androidx.compose.material", name = "material-icons-extended" }

gradle = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinGradlePlugin" }

# Testing
androidx-test-junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "extJunit" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }

# hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "daggerHilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "daggerHilt" }
hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "androidxHilt" }
hilt-nav-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidxHilt" }

#work
androidx-work-runtime = { group = "androidx.work", name = "work-runtime", version.ref = "work" }
work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work" }
work-testing = { group = "androidx.work", name = "work-testing", version.ref = "work" }

#firebase
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ndk" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }

#room
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-testing = { group = "androidx.room", name = "room-testing", version.ref = "room" }

#other
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
security-crypto = { group = "androidx.security", name = "security-crypto", version.ref = "security" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

[bundles]
androidx = ["androidx-core-ktx", "androidx-lifecycle-runtime-ktx", "androidx-activity-compose"]
compose-ui = ["androidx-compose-ui", "androidx-compose-ui-graphics", "androidx-compose-ui-tooling-preview", "androidx-material3", "androidx-compose-icons"]
compose-debug = ["androidx-compose-ui-tooling", "androidx-compose-ui-test-manifest"]
androidx-test = ["androidx-test-ext-junit", "androidx-test-espresso-core"]
hilt = ["hilt-android", "hilt-work", "hilt-nav-compose"]
work = ["androidx-work-runtime", "work-runtime-ktx", "work-testing"]
firebase = ["firebase-crashlytics", "firebase-analytics"]
room = ["room-runtime", "room-testing"]

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServicesGradlePlugin" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlyticsGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlinComposeCompiler" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detektGradlePlugin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "daggerHilt" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinSerialization" }
