[versions]
androidGradlePlugin = "8.13.2"
kotlinGradlePlugin = "1.9.24"
googleServicesGradlePlugin = "4.4.4"
crashlyticsGradlePlugin = "3.0.6"
detektGradlePlugin = "1.23.8"

junit = "4.13.2"
extJunit = "1.3.0"
testRunner = "1.7.0"
espressoCore = "3.7.0"
mockk = "1.14.9"
kotlinxCoroutineTest = "1.10.2"
truth = "1.4.5"

composeBom = "2026.01.01"
firebaseBom = "34.8.0"

kotlin = "2.3.0"
kotlinComposeCompiler = "2.3.0"
ksp = "2.3.5"
kotlinSerialization = "2.3.0"
coreKtx = "1.17.0"
lifecycleRuntimeKtx = "2.10.0"
lifecycleProcess = "2.10.0"
activityCompose = "1.12.3"
navigationCompose = "2.9.7"
material3 = "1.4.0"
daggerHilt = "2.58"
androidxHilt = "1.3.0"
work = "2.11.1"
timber = "5.0.1"
room = "2.8.4"
security = "1.1.0"
kotlinxSerializationJson = "1.10.0"
biometric = "1.1.0"
playReview = "2.0.2"
dataStore = "1.2.0"

[libraries]
# AndroidX Core
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "lifecycleProcess" }

# Compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-compose-icons = { group = "androidx.compose.material", name = "material-icons-extended" }


gradle = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinGradlePlugin" }

# Testing
androidx-test-junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "extJunit" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "testRunner" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutineTest" }
truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }

# Mockito
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
mockk-agent = { group = "io.mockk", name = "mockk-agent", version.ref = "mockk" }
mockk-android = { group = "io.mockk", name = "mockk-android", version.ref = "mockk" }

# hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "daggerHilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "daggerHilt" }
hilt-nav-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidxHilt" }

#work
work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work" }
work-testing = { group = "androidx.work", name = "work-testing", version.ref = "work" }

#firebase
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }

#room
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-testing = { group = "androidx.room", name = "room-testing", version.ref = "room" }

#other
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
security-crypto = { group = "androidx.security", name = "security-crypto", version.ref = "security" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
biometric = { group = "androidx.biometric", name = "biometric", version.ref = "biometric" }
play-review = { group = "com.google.android.play", name = "review", version.ref = "playReview" }
play-review-ktx = { group = "com.google.android.play", name = "review-ktx", version.ref = "playReview" }
data-store-pref = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "dataStore" }

[bundles]
androidx = ["androidx-core-ktx", "androidx-lifecycle-runtime-ktx", "androidx-activity-compose", "androidx-navigation-compose", "lifecycle-process"]
compose-ui = ["androidx-compose-ui", "androidx-compose-ui-graphics", "androidx-compose-ui-tooling-preview", "androidx-material3", "androidx-compose-icons"]
compose-debug = ["androidx-compose-ui-tooling", "androidx-compose-ui-test-manifest"]
unit-test = ["androidx-test-ext-junit", "androidx-test-junit", "mockk", "mockk-agent", "kotlinx-coroutines-test", "truth"]
hilt = ["hilt-android", "hilt-nav-compose"]
work = ["work-runtime-ktx", "work-testing"]
firebase = ["firebase-crashlytics", "firebase-analytics"]
room = ["room-runtime", "room-testing"]
play-review = ["play-review", "play-review-ktx"]

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServicesGradlePlugin" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlyticsGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlinComposeCompiler" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detektGradlePlugin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "daggerHilt" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinSerialization" }
