name: CI & Internal Distribution

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6

      - name: set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Verify NDK Gatekeeper
        run: |
          # 1. Extract the ndk version from app/build.gradle
          REQUIRED_NDK=$(grep "ndkVersion" app/build.gradle | sed "s/.*ndkVersion//" | tr -d "[:space:]'\"")
          
          echo "Checking for NDK Version: [$REQUIRED_NDK]"
          
          NDK_PATH="$ANDROID_HOME/ndk/$REQUIRED_NDK"
          
          # 2. Check if that specific directory exists
          if [ ! -d "$NDK_PATH" ]; then
            echo "::error::NDK Version $REQUIRED_NDK not found on CI runner!"
            echo "Expected path: $NDK_PATH"
            echo "Actually available in $ANDROID_HOME/ndk/:"
            ls "$ANDROID_HOME/ndk/"
            exit 1
          else
            echo "âœ… NDK $REQUIRED_NDK found and verified."
          fi

      - name: Set release key store Properties
        env:
          RELEASE_KEYSTORE_PROPERTIES: ${{ secrets.RELEASE_KEYSTORE_PROPERTIES }}
        run: echo "$RELEASE_KEYSTORE_PROPERTIES" > ./releaseKeyStore.properties

      - name: Prepare keystore
        run: |
          echo "${{ secrets.BASE_64_RELEASE_KEYSTORE }}" > ./releaseKeyStore.jks.asc
          gpg -d --passphrase "${{ secrets.GPG_PASSPHRASE }}" --batch ./releaseKeyStore.jks.asc > ./app/releaseKeyStore.jks

      - name: Prepare google services json
        run: |
          echo "${{ secrets.BASE_64_GOOGLE_SERVICES_JSON }}" > ./app/google-services.json.asc
          gpg -d --passphrase "${{ secrets.GPG_PASSPHRASE }}" --batch ./app/google-services.json.asc > ./app/google-services.json

      - name: Build release bundle
        run: ./gradlew bundleRelease

      - name: upload symbols file
        run: ./gradlew uploadCrashlyticsSymbolFileRelease

      - name: upload release bundle
        uses: actions/upload-artifact@v6
        with:
          name: release aab
          path: app/build/outputs/bundle/release/*.aab
          retention-days: 1

      - name: inspect AAB for symbols
        run: unzip -l app/build/outputs/bundle/release/*.aab | grep "BUNDLE-METADATA"