name: CI & Internal Distribution

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      build_qa:
        description: 'Check to build QA APK as well'
        required: false
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: .github/workflows/setup/setup.yml

  quality:
    needs:
      - setup
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: ./.github/workflows/setup/quality.yml

  debug_apk:
    needs:
      - setup
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Build debug apk
        run: ./gradlew assembleDebug --scan

      - name: upload debug apk
        uses: actions/upload-artifact@v6
        with:
          name: debug app
          path: app/build/outputs/apk/debug/SafeBox-debug.apk

  qa_apk:
    if: ${{ github.event.inputs.build_qa == 'true' }}
    needs:
      - setup
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Build QA apk
        run: ./gradlew assembleQa --scan

      - name: upload symbols file
        run: ./gradlew uploadCrashlyticsSymbolFileQa

      - name: Upload QA APK
        uses: actions/upload-artifact@v6
        with:
          name: ${{ github.event_name == 'pull_request' && format('SafeBox-QA-PR-{0}', github.event.pull_request.number) || 'SafeBox-QA-Master' }}
          path: app/build/outputs/apk/qa/*.apk
          retention-days: 7