name: CI & Internal Distribution

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-encryption-key: ${{secrets.GRADLE_ENCRYPTION_KEY }}
          cache-read-only: false

      - name: Run lint
        run: ./gradlew lintDebug

      - name: upload html lint report
        uses: actions/upload-artifact@v6
        with:
          name: lint result
          path: app/build/reports/lint-results-debug.html

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: upload test result
        if: always() # Upload even if tests fail
        uses: actions/upload-artifact@v6
        with:
          name: Unit test result
          path: app/build/reports/tests/testDebugUnitTest/

  debug_pipeline:
    needs:
      - quality
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-encryption-key: ${{secrets.GRADLE_ENCRYPTION_KEY }}
          cache-read-only: false

      - name: Build debug apk
        run: ./gradlew assembleDebug --scan

      - name: upload debug apk
        uses: actions/upload-artifact@v6
        with:
          name: debug app
          path: app/build/outputs/apk/debug/SafeBox-debug.apk

  qa_pipeline:
    needs:
      - quality
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-encryption-key: ${{secrets.GRADLE_ENCRYPTION_KEY }}
          cache-read-only: false

      - name: Build QA apk
        run: ./gradlew assembleQa --scan

      - name: Upload QA APK
        uses: actions/upload-artifact@v6
        with:
          name: ${{ github.event_name == 'pull_request' && format('SafeBox-QA-PR-{0}', github.event.pull_request.number) || 'SafeBox-QA-Master' }}
          path: app/build/outputs/apk/qa/*.apk
          retention-days: 7

      - name: upload QA mapping file
        uses: actions/upload-artifact@v6
        with:
          name: qaMapping
          path: app/build/outputs/mapping/qa/mapping.txt

      - name: upload QA symbols file to crashlytics
        run: ./gradlew uploadCrashlyticsSymbolFileQa