name: CI & Internal Distribution

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/workflows/setup
        with:
          gradle_key: ${{secrets.GRADLE_ENCRYPTION_KEY }}

  #      - name: Build debug apk
  #        run: ./gradlew assembleDebug --info --scan
  
  #  quality:
  #    needs:
  #      - setup
  #    runs-on: ubuntu-latest
  #    permissions:
  #      contents: read
  #    steps:
  #      - uses: actions/checkout@v6
  #      - uses: ./.github/workflows/quality

  debug_apk:
    needs:
      - setup
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - name: Build debug apk
        run: ./gradlew assembleDebug --info --scan
#
#      - name: upload debug apk
#        uses: actions/upload-artifact@v6
#        with:
#          name: debug app
#          path: app/build/outputs/apk/debug/SafeBox-debug.apk

#  qa_apk:
#    needs:
#      - setup
#    runs-on: ubuntu-latest
#    permissions:
#      contents: read
#    steps:
#      - uses: actions/checkout@v6
#      - name: Build QA apk
#        run: ./gradlew assembleQa --scan
#
#      - name: upload symbols file
#        run: ./gradlew uploadCrashlyticsSymbolFileQa
#
#      - name: Upload QA APK
#        uses: actions/upload-artifact@v6
#        with:
#          name: ${{ github.event_name == 'pull_request' && format('SafeBox-QA-PR-{0}', github.event.pull_request.number) || 'SafeBox-QA-Master' }}
#          path: app/build/outputs/apk/qa/*.apk
#          retention-days: 7