name: Production & RC Release

on:
  push:
    tags: [ 'v*' ] # Triggers for v1.2.0, v1.2.0-rc1, etc. tag push

jobs:
  quality:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: verify label
        uses: actions/github-script@v8
        with:
          script: |
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });
            
            if (pr.labels.length === 0) {
              core.setFailed("âŒ Please add at least one label.");
            } else {
              console.log(`âœ… Labels found.`);
            }      

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-encryption-key: ${{secrets.GRADLE_ENCRYPTION_KEY }}
          cache-read-only: false

      - name: Run lint
        run: ./gradlew lintRelease

      - name: upload html lint report
        uses: actions/upload-artifact@v6
        with:
          name: lint result
          path: app/build/reports/lint-results-release.html

      - name: Run Unit Tests
        run: ./gradlew testReleaseUnitTest

      - name: upload test result
        if: always() # Upload even if tests fail
        uses: actions/upload-artifact@v6
        with:
          name: Unit test result
          path: app/build/reports/tests/testReleaseUnitTest/

      - name: Verify NDK Gatekeeper
        run: |
          # 1. Extract the ndk version from app/build.gradle
          REQUIRED_NDK=$(grep "ndkVersion" app/build.gradle | sed "s/.*ndkVersion//" | tr -d "[:space:]'\"")
          
          echo "Checking for NDK Version: [$REQUIRED_NDK]"
          
          NDK_PATH="$ANDROID_HOME/ndk/$REQUIRED_NDK"
          
          # 2. Check if that specific directory exists
          if [ ! -d "$NDK_PATH" ]; then
            echo "::error::NDK Version $REQUIRED_NDK not found on CI runner!"
            echo "Expected path: $NDK_PATH"
            echo "Actually available in $ANDROID_HOME/ndk/:"
            ls "$ANDROID_HOME/ndk/"
            exit 1
          else
            echo "âœ… NDK $REQUIRED_NDK found and verified."
          fi

  debug_pipeline:
    needs:
      - quality
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-encryption-key: ${{secrets.GRADLE_ENCRYPTION_KEY }}
          cache-read-only: false

      - name: Build debug apk
        run: ./gradlew assembleDebug --scan

      - name: upload debug apk
        uses: actions/upload-artifact@v6
        with:
          name: debug app
          path: app/build/outputs/apk/debug/SafeBox-debug.apk

  release_pipeline:
    needs:
      - debug_pipeline
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-encryption-key: ${{secrets.GRADLE_ENCRYPTION_KEY }}
          cache-read-only: false

      - name: Set release key store Properties
        env:
          RELEASE_KEYSTORE_PROPERTIES: ${{ secrets.RELEASE_KEYSTORE_PROPERTIES }}
        run: echo "$RELEASE_KEYSTORE_PROPERTIES" > ./releaseKeyStore.properties

      - name: Prepare keystore
        run: |
          echo "${{ secrets.BASE_64_RELEASE_KEYSTORE }}" > ./releaseKeyStore.jks.asc
          gpg -d --passphrase "${{ secrets.GPG_PASSPHRASE }}" --batch ./releaseKeyStore.jks.asc > ./app/releaseKeyStore.jks

      - name: Prepare google services json
        run: |
          echo "${{ secrets.BASE_64_GOOGLE_SERVICES_JSON }}" > ./app/google-services.json.asc
          gpg -d --passphrase "${{ secrets.GPG_PASSPHRASE }}" --batch ./app/google-services.json.asc > ./app/google-services.json

      - name: Build release bundle
        run: ./gradlew bundleRelease

      - name: upload release bundle
        uses: actions/upload-artifact@v6
        with:
          name: release aab
          path: app/build/outputs/bundle/release/*.aab
          retention-days: 7

      - name: upload symbols file
        run: ./gradlew uploadCrashlyticsSymbolFileRelease

  qa_pipeline:
    needs:
      - quality
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-encryption-key: ${{secrets.GRADLE_ENCRYPTION_KEY }}
          cache-read-only: false

      - name: Build QA apk
        run: ./gradlew assembleQa --scan

      - name: upload QA apk
        uses: actions/upload-artifact@v6
        with:
          name: QA APK
          path: app/build/outputs/apk/qa/*.apk
          retention-days: 7

      - name: upload QA mapping file
        uses: actions/upload-artifact@v6
        with:
          name: qaMapping
          path: app/build/outputs/mapping/qa/mapping.txt

      - name: upload QA symbols file to crashlytics
        run: ./gradlew uploadCrashlyticsSymbolFileQa

  release_on_github:
    needs:
      - qa_pipeline
      - release_pipeline
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Retrieve QA apk
        uses: actions/download-artifact@v7
        with:
          name: QA APK
          path: downloaded-artifacts/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ contains(github.ref_name, 'rc') || contains(github.ref_name, 'beta') }}
          generate_release_notes: true # This pulls logic from .github/release.yml
          body: |
            ${{ contains(github.ref_name, 'rc') && 'ðŸ§ª This is a **Release Candidate** for testing purposes.' || 'ðŸš€ This is a **Stable Production** release.' }}
          files: downloaded-artifacts/*